version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"

  haproxy:
    build:
      context: .
      dockerfile: Dockerfile-haproxy
    ports:
      - "80:80"
    # Lier HAProxy aux instances de l'application
    depends_on:
      - app1
      - app2
