version: '3.8'

services:
  motus:
    build:
      context: ./motus
    ports:
      - "3000:3000"

  score:
    build:
      context: ./score
    ports:
      - "3001:3000"
      
  #authentifications:
    #build:
      #context: ./authentifications
    #ports:
      #- "3002:3000"
